### ISSUE TITLE
Ability to save playlist from youtube playlist link

### ISSUE THREAD

**Issue by sanihaq** [iamsainikhil/trimtube#11]
**Is your feature request related to a problem? Please describe.**
it's really a pain to add video one by one, when I already have playlist created in youtube.

**Describe the solution you'd like**
add all videos from a playlist link and create a playlist with the same name

**Comment by iamsainikhil** [comment]
Thanks @sanihaq! That's a very good feature and I honestly missed it somehow in the app. 

I will try to add this feature ASAP.

**Comment by sanihaq** [comment]
@iamsainikhil hey, I just want to add playlist created with a playlist link should auto update or at least have a button to update the playlist. anyway, keep up the good work. 👍

**Comment by iamsainikhil** [comment]
@sanihaq I have finished implementing this feature. Could you take a look at the demo and let me know your feedback?

PR - https://github.com/iamsainikhil/trimtube/pull/12

Demo - https://vimeo.com/673967473

**Comment by iamsainikhil** [comment]
The reason I went with creating the YT playlist in TrimTube with arbitrary name like `Untitled` or `Untitled-copy` is because the YouTube API response does not include metadata about the playlist itself, such as the playlist's title and description. 

Additional metadata about the videos in the playlist can also be retrieved using the [videos.list](https://developers-dot-devsite-v2-prod.appspot.com/youtube/v3/docs/videos/list) method which is an another API request.

To reduce API requests, I just went creating a playlist with the above names. However, I have added the functionality to edit a playlist name which should allow user to change the name.

**Comment by sanihaq** [comment]
@iamsainikhil this is great so far. please add a refresh button so playlist can be updated. I think it'll open up many more opportunities.

**Comment by iamsainikhil** [comment]
Thanks @sanihaq. 

App doesn't support the URL format for the playlist search. So, you need to just paste the playlist ID and it should work.

The reason for doing this is because a playlist link could be:
1. https://www.youtube.com/playlist?list=PLeLvSt3A0Ddk9lGjNqmzT0ctVPA5xfinn
2. https://www.youtube.com/watch?v=XXYTRE34580eu&list=PLeLvSt3A0Ddk9lGjNqmzT0ctVPA5xfinn

**Comment by sanihaq** [comment]
@iamsainikhil  ohh, sorry my bad! got used to pasting video url.

**Comment by iamsainikhil** [comment]
I can use a regex to grab the playlist ID which should solve the above issue. 😄

Regex - https://regex101.com/r/mI3qY9/6

**Comment by sanihaq** [comment]
@iamsainikhil  also, I think sorting playlist video by date (or a full blow sorting feature) would be great along with a update list button. shouldn't have any api overhead local sorting will do. Thanks. Your hard work is very much apriciated

**Comment by iamsainikhil** [comment]
@sanihaq I have actually started working on it (sort) feature with ability to drag the videos in the playlists 😉.

However, I am busy working on making the YouTube video iframe autoplay video on mobile devices. This is an important problem to tackle compared to the above features.

Issue : https://github.com/iamsainikhil/trimtube/issues/14

**Comment by iamsainikhil** [comment]
> @iamsainikhil also, I think sorting playlist video by date (or a full blown sorting feature) would be great along with a update list button. shouldn't have any api overhead local sorting will do. Thanks. Your hard work is very much appreciated.

@sanihaq could you create a issue (feature request) for this so it would be easy to track the progress?

**Comment by sanihaq** [comment]
@iamsainikhil Ok. there's no rush, wish I could've helped, unfortunately I don't have much experience with next.js or react for that matter. 😟
